### ISSUE TITLE
Does not work inside saferoom

### ISSUE THREAD

**Issue by lunatixxx** [Psykotikism/No_Friendly-Fire#4]
What to change to enable it when survivors are in the saferoom but to disable it everywhere else ?

**Comment by Psykotikism** [comment]
I'm confused by the title of your issue. Are you asking to have an option that only blocks friendly-fire inside the saferoom or are you saying that it doesn't block friendly-fire in the saferoom?

**Comment by lunatixxx** [comment]
I would like a setting where the friendly fire is only blocked when survivor are still the saferoom, once they go out and that the map has started then the friendly fire is now on .

**Comment by Psykotikism** [comment]
I will add this option in the next update.

**Comment by lunatixxx** [comment]
Thank you. With left4dhooks there is a setting "L4D_HasAnySurvivorLeftSafeArea", but i did not know what to modify.
